//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace EF_test1.Models
{
    public partial class PermissionDBEntities : ObjectContext
    {
        public const string ConnectionString = "name=PermissionDBEntities";
        public const string ContainerName = "PermissionDBEntities";
    
        #region Constructors
    
        public PermissionDBEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public PermissionDBEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public PermissionDBEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<role> role
        {
            get { return _role  ?? (_role = CreateObjectSet<role>("role")); }
        }
        private ObjectSet<role> _role;
    
        public ObjectSet<userrole> userrole
        {
            get { return _userrole  ?? (_userrole = CreateObjectSet<userrole>("userrole")); }
        }
        private ObjectSet<userrole> _userrole;
    
        public ObjectSet<users> users
        {
            get { return _users  ?? (_users = CreateObjectSet<users>("users")); }
        }
        private ObjectSet<users> _users;

        #endregion
    }
}
